---
- name: install git & zsh
  apt:
    name: {{ packages }}
    state: present
  vars:
    packages:
      - git
      - zsh

- name: get prezto installer
  get_url: url=https://github.com/loranger/prezto/raw/master/go.sh dest=/tmp/install_prezto.sh mode="a+x"

- name: use zsh shell for users
  user: name={{ item }} shell='/usr/bin/zsh'
  with_items: "{{ prezto.users }}"

- name: install prezto
  shell: /tmp/install_prezto.sh
  become: yes
  become_user: "{{ item }}"
  with_items: "{{ prezto.users }}"

- name: set prezto prompt theme
  lineinfile: dest=/home/{{ item }}/.zprezto/runcoms/zpreztorc regexp="prezto:module:prompt" line="zstyle ':prezto:module:prompt' theme {{ prezto.prompt }}"
  with_items: "{{ prezto.users }}"
