---
- name: install git & zsh
  apt: pkg={{ item }} state=present
  with_items:
    - git
    - zsh

- name: get prezto installer
  get_url: url=https://github.com/loranger/prezto/raw/master/go.sh dest=/tmp/install_prezto.sh mode="a+x"

- name: use zsh shell for users
  user: name={{ item }} shell='/usr/bin/zsh'
  with_items: prezto_users

- name: install prezto
  shell: /tmp/install_prezto.sh
  sudo_user: "{{ item }}"
  with_items: prezto_users

- name: set cloud prompt theme
  lineinfile: dest=/home/{{ item }}/.zprezto/runcoms/zpreztorc regexp="prezto:module:prompt" line="zstyle ':prezto:module:prompt' theme 'cloud' '☁️'"
  with_items: prezto_users